# docker-compose up -d

version: '3.8'
services:
  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - '6379:6379'
    restart: unless-stopped
    command: redis-server --maxmemory 128mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
